<?php
    /**
     * @var \Magento\Framework\View\Element\Template
     * @var \Magefan\MyModule\ViewModel\View $viewModel
     */
    $viewModel = $block->getData('viewModel');

    echo $block->escapeHtml($viewModel->sayHello());
?>

        <style>
            table {
                font-family: arial, sans-serif;
                border-collapse: collapse;
                width: 100%;
                margin-top: 30px;
            }

            td, th {
                border: 1px solid #dddddd;
                text-align: left;
                padding: 8px;
            }

            tr:nth-child(even) { 
                background-color: #dddddd; 
            }

            .greeting-id {
                width:2%;
            }

            .greeting-message {
                width:30%;
            }
        </style>

        <table>
            <tr>
                <th class="greeting-id">Id</th>
                <th class="greeting-message">Message</th>
                <th class="greeting-message">Season</th>
            </tr>
            <?php
                foreach ($viewModel->getGreetingMessageCollection() as $key => $message) {
                    echo '<tr>
                    <td>'.$block->escapeHtml($message->getGreetingId()).'</td>
                    <td>'.$block->escapeHtml($message->getMessage()).'</td>
                    <td>'.$block->escapeHtml($message->getSeason()).'</td>
                    </tr>';
                }
            ?>
        </table>
    </body>
</html>